name: CI

# Controls when the action will run.
on:
  push:
    branches: [master, next, stable, staging]
  pull_request:
    branches: [master, next, stable, staging]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Cache build cache and downloads
        uses: actions/cache@v2
        env:
          cache-name: cache-buildroot
        with:
          path: ~/br-cache/
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Install buildroot apt deps
        run: |
          sudo apt-get install -y libelf-dev

      - name: Print help and packages list
        run: |
          cd $GITHUB_WORKSPACE
          make help

      - name: Build a Docker container image
        run: |
          cd $GITHUB_WORKSPACE
          export TERM=xterm
          export BR2_CCACHE_DIR=${HOME}/br-cache/ccache
          export BR2_DL_DIR=${HOME}/br-cache/dl
          export SKIFF_WORKSPACE=docker
          export SKIFF_CONFIG=virt/docker,skiff/core
          make -s configure compile check
          echo "Compilation complete, building Docker image..."
          make cmd/virt/docker/buildimage
          sleep 2 # docker sometimes does not tag right away
          mkdir -p workflow-artifacts
          docker save skiffos/skiffos:latest > ./workflow-artifacts/docker-image.tar

      # Upload docker image
      - uses: actions/upload-artifact@v2
        with:	
          name: docker-image.tar
          path: ${{ github.workspace }}/workflow-artifacts/docker-image.tar

